version: '3.0'

services:
    express-template:
        build: .
        command: npm start
        volumes:
            - ./controllers/:/controllers/
            - ./routes/:/routes/
            - ./middlewares/:/middlewares/
        ports:
            - 8080:8080
